version: "3.8"

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: suraj
      MONGO_INITDB_ROOT_PASSWORD: kota

  
  mongo-express:
    image: mongo-express
    ports:
    - 8081-8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: suraj
      ME_CONFIG_MONGODB_ADMINPASSWORD: kota
      ME_CONFIG_MONGODB_URL: MONGODB://suraj:kota@mongo:27017/